---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: doc-builder
  namespace: d8-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: d8-system
  name: configmap-write
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: doc-builder
  namespace: d8-system
subjects:
  - kind: ServiceAccount
    name: doc-builder
    namespace: d8-system
roleRef:
  kind: Role
  name: configmap-write
  apiGroup: rbac.authorization.k8s.io
