---
apiVersion: v1
kind: Secret
metadata:
  name: d8-node-manager-cloud-provider
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: Opaque
data:
  type: {{ b64enc "vcd" | quote }}
  region: default
  zones:
  - "default"
  instanceClassKind: {{ b64enc "VCDInstanceClass" | quote }}
  machineClassKind: ""
  vcd: "{}"
