---
apiVersion: v1
kind: Secret
metadata:
  name: d8-node-manager-cloud-provider
  namespace: kube-system
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: Opaque
data:
  type: {{ b64enc "vcd" | quote }}
  region: {{ b64enc "default" | quote }}
  zones: {{ b64enc "[\"default\"]" | quote }}
  instanceClassKind: {{ b64enc "VCDInstanceClass" | quote }}
  machineClassKind: {{ b64enc "" | quote }}
  vcd: {{ b64enc "{}" | quote }}
