---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gost-digest-webhook
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "gost-digest-webhook")) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app: gost-digest-webhook
