---
apiVersion: v1
kind: Service
metadata:
  name: gost-digest-webhook
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "gost-digest-webhook")) | nindent 2 }}
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 9443
    targetPort: 9443
  - name: metrics
    port: 8085
    targetPort: 8085
  selector:
    app: gost-digest-webhook

