{{- if .Values.global.clusterIsBootstrapped }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gost-digest-webhook
  {{- include "helm_lib_module_labels" (list . (dict "app" "gost-digest-webhook")) | nindent 2 }}
webhooks:
  - name: gost-digest-webhook.deckhouse.io
    namespaceSelector:
      matchExpressions:
        - key: deckhouse.io/gost-digest-validation-enabled
          operator: In
          values: ["true"]
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
        operations:
          - CREATE
        scope: Namespaced
    admissionReviewVersions:
      - v1
    matchPolicy: Equivalent
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      caBundle: {{ .Values.gostIntegrityController.internal.admissionWebhookCert.ca | b64enc }}
      service:
        name: gost-digest-webhook
        namespace: d8-system
        port: 9443
        path: /validate
{{- end }}
