---
apiVersion: v1
kind: Secret
metadata:
  name: loki-access-tokens
  namespace: d8-monitoring
    {{- include "helm_lib_module_labels" (list . (dict "app" .Chart.Name)) | nindent 2 }}
data:
  grafanaToken: {{ .Values.loki.internal.grafanaToken | b64enc }}
  logShipperToken: {{ .Values.loki.internal.logShipperToken | b64enc }}
