{{- if .Values.nodeManager.internal.capsControllerManagerEnabled }}
{{- $prefix := "static" }}
{{- $provider := "static" }}
  {{- if .Values.nodeManager.internal.capsControllerManagerClusterEnabled }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ $prefix }}
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "caps-controller-manager")) | nindent 2 }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - {{ .Values.global.clusterConfiguration.podSubnetCIDR }}
    services:
      cidrBlocks:
        - {{ .Values.global.clusterConfiguration.serviceSubnetCIDR }}
    serviceDomain: {{ .Values.global.clusterConfiguration.clusterDomain }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: StaticCluster
    namespace: d8-cloud-instance-manager
    name: {{ $prefix }}
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: StaticControlPlane
    namespace: d8-cloud-instance-manager
    name: {{ $prefix }}-control-plane
  {{- end }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StaticCluster
metadata:
  namespace: d8-cloud-instance-manager
  name: {{ $prefix }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "caps-controller-manager")) | nindent 2 }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: StaticControlPlane
metadata:
  namespace: d8-cloud-instance-manager
  name: {{ $prefix }}-control-plane
  {{- include "helm_lib_module_labels" (list . (dict "app" "caps-controller-manager" "cluster.x-k8s.io/cluster-name" $prefix)) | nindent 2 }}
{{- end }}
