properties:
  apiKey:
    description: |
      Ключ для доступа к API Okmeter.

      Ключ можно получить в личном кабинете Okmeter.
  disableAutoDiscovery:
    description: |
      Отключит автоматическое обнаружение сервисов, которые способен мониторить okmeter. Значение `true` оставит базовый мониторинг хоста, прочие плагины (postgresql, mysql, redis и др.) будут отключены.

      По умолчанию установлено значение `false`.
  nodeSelector:
    description: |
      Структура, аналогичная `spec.nodeSelector` пода Kubernetes.

      Если ничего не указано или указано `false`, то Deckhouse попытается вычислить значение `nodeSelector` [автоматически](https://deckhouse.ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  tolerations:
    description: |
      Структура, аналогичная `spec.tolerations` пода Kubernetes.

      Если ничего не указано или указано `false`, то Deckhouse попытается вычислить значение `tolerations` [автоматически](https://deckhouse.ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  image:
    repository:
      description: Репозиторий с образом для okmeter agent.
    tag:
      description: Tag образа для okmeter agent.
