---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    heritage: deckhouse
    module: deckhouse
  name: projecttemplates.deckhouse.io
spec:
  group: deckhouse.io
  names:
    kind: ProjectTemplate
    listKind: ProjectTemplateList
    plural: projecttemplates
    singular: projecttemplate
  scope: Cluster
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - jsonPath: .status.ready
          name: Ready
          type: boolean
      schema:
        openAPIV3Schema:
          description: |
            Describes the project template.

            This resource is referenced by the [Project](cr.html#project) CR.
          properties:
            spec:
              properties:
                namespaceMetadata:
                  description:
                    Labels and annotations that apply to created
                    namespaces when setting up the project.
                  properties:
                    annotations:
                      additionalProperties:
                        type: string
                      type: object
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                valuesSchema:
                  additionalProperties:
                    x-kubernetes-preserve-unknown-fields: true
                  description:
                    OpenAPI specification for template values (the [template](#projecttemplate-v1alpha1-spec-template) parameter).
                  type: object
                template:
                  description: |
                    Templates in `helm` format to be created when setting up a new project.

                    Templates are fully compatible with all `helm` functions. Read more about [creating an isolated Environment](usage.html#creating-an-isolated-environment)...

                    The following values are also available in templates:
                    - `{{ .projectName }}` — the name of the `Project` (project) for which the template is being rendered.
                    - `{{ .templateName }}` — the name of the `ProjectTemplate`.
                    - `{{ .templateValues }}` — a dictionary of custom values, described in the [.spec.valuesSchema](cr.html#projecttemplate-v1alpha1-spec-valuesSchema) parameter and defined in the [.spec.template](cr.html#project-v1alpha1-spec-template) parameter.

                    > **Note!** Specifying `.metadata.namespace` fields for objects is optional,
                    > as they are automatically set with the name of the created project.
                  type: string
              type: object
            status:
              properties:
                message:
                  description: Status message.
                  type: string
                ready:
                  description: Summary of the status (ready or not ready).
                  type: boolean
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
