{{- define "registry_packages_proxy_resources" }}
cpu: 250m
memory: 500Mi
{{- end }}

{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: registry-packages-proxy
  namespace: d8-registry-packages-proxy
  {{- include "helm_lib_module_labels" (list . (dict "app" "registry-packages-proxy" "workload-resource-policy.deckhouse.io" "master")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: registry-packages-proxy
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
    - containerName: "registry-packages-proxy"
      minAllowed:
        {{- include "registry_packages_proxy_resources" . | nindent 8 }}
      maxAllowed:
        cpu: 500m
        memory: 500Mi
    {{- include "helm_lib_vpa_kube_rbac_proxy_resources" . | nindent 4 }}
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: registry-packages-proxy
  namespace: d8-registry-packages-proxy
  {{- include "helm_lib_module_labels" (list . (dict "app" "registry-packages-proxy")) | nindent 2 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: registry-packages-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-packages-proxy
  namespace: d8-registry-packages-proxy
  {{- include "helm_lib_module_labels" (list . (dict "app" "registry-packages-proxy")) | nindent 2 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: registry-packages-proxy
  template:
    metadata:
      labels:
        app: registry-packages-proxy
      annotations:
        kubectl.kubernetes.io/default-exec-container: registry-packages-proxy
        kubectl.kubernetes.io/default-logs-container: registry-packages-proxy
    spec:
      {{- include "helm_lib_priority_class" (tuple . "cluster-low") | nindent 6 }}
      {{- include "helm_lib_node_selector" (tuple . "master") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "any-node") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_deckhouse" . | nindent 6 }}
      hostNetwork: true
      serviceAccountName: registry-packages-proxy
      containers:
      - name: registry-packages-proxy
        {{- include "helm_lib_module_container_security_context_not_allow_privilege_escalation" . | nindent 8 }}
        image: {{ include "helm_lib_module_image" (list . "registryPackagesProxy") }}
        args:
        - --discovery-period=1h
        - --listen-address=:8081
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTPS
        resources:
          requests:
            {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 12 }}
          {{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
            {{- include "registry_packages_proxy_resources" . | nindent 12 }}
          {{- end }}
      - name: kube-rbac-proxy
        {{- include "helm_lib_module_container_security_context_read_only_root_filesystem" . | nindent 8 }}
        image: {{ include "helm_lib_module_common_image" (list . "kubeRbacProxy") }}
        args:
          - "--secure-listen-address=$(KUBE_RBAC_PROXY_LISTEN_ADDRESS):8080"
          - "--v=2"
          - "--logtostderr=true"
          - "--stale-cache-interval=1h30m"
        ports:
          - containerPort: 8080
            name: https-metrics
        env:
          - name: KUBE_RBAC_PROXY_LISTEN_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBE_RBAC_PROXY_CONFIG
            value: |
              excludePaths:
              - /healthz
              upstreams:
              - upstream: http://127.0.0.1:8081/
                path: /
                authorization:
                  resourceAttributes:
                    namespace: d8-registry-packages-proxy
                    apiGroup: apps
                    apiVersion: v1
                    resource: deployments
                    subresource: prometheus-metrics
                    name: registry-packages-proxy
        resources:
          requests:
            {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 12 }}
          {{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
            {{- include "helm_lib_container_kube_rbac_proxy_resources" . | nindent 12 }}
          {{- end }}
