{{/* KubeDNS is not installed on the bootstrap phase and kube-apiserver will fail on a DNS resolution request */}}
{{/*   because it doesn't know `deckhouse.d8-system.svc` address yet.*/}}
{{- if .Values.global.clusterIsBootstrapped }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-handler-certs
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhook-handler")) | nindent 2 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.deckhouse.internal.webhookHandlerCert.crt | b64enc | quote }}
  tls.key: {{ .Values.deckhouse.internal.webhookHandlerCert.key | b64enc | quote }}
  ca.crt: {{ .Values.deckhouse.internal.webhookHandlerCert.ca  | b64enc | quote }}
{{- end }}
