{{/* KubeDNS is not installed on the bootstrap phase and kube-apiserver will fail on a DNS resolution request */}}
{{/*   because it doesn't know `deckhouse.d8-system.svc` address yet.*/}}
{{- if .Values.global.clusterIsBootstrapped }}
---
apiVersion: v1
kind: Service
metadata:
  name: validating-webhook-handler
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhook-handler")) | nindent 2 }}
spec:
  ports:
    - name: validating-webhook
      port: 443
      targetPort: 9680
      protocol: TCP
  selector:
    app: webhook-handler
---
apiVersion: v1
kind: Service
metadata:
  name: conversion-webhook-handler
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhook-handler")) | nindent 2 }}
spec:
  ports:
    - name: conversion-webhook
      port: 443
      targetPort: 9681
      protocol: TCP
  selector:
    app: webhook-handler
{{- end }}
