apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticclusters.infrastructure.cluster.x-k8s.io
  labels:
    heritage: deckhouse
    module: node-manager
spec:
  group: infrastructure.cluster.x-k8s.io
  # cluster wide resource
  names:
    kind: StaticClusters
    plural: staticclusters
    singular: staticcluster
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      additionalPrinterColumns:
        - name: Age
          type: date
          description: >
            CreationTimestamp is a timestamp representing the server time when this object was created.
            It is not guaranteed to be set in happens-before order across separate operations.
            Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          description: |
            Defines the static cluster.
          properties:
          status:
            type: object
            description: Most recently observed status of the static cluster.
            properties:
              ready:
                type: boolean
                description: Indicates the provider-specific infrastructure has been provisioned and is ready.
              failureReason:
                type: string
                description: Indicates there is a fatal problem reconciling the provider’s infrastructure; meant to be suitable for programmatic interpretation
              failureMessage:
                type: string
                description: Indicates there is a fatal problem reconciling the provider’s infrastructure; meant to be a more descriptive value than failureReason
