apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticmachines.infrastructure.cluster.x-k8s.io
  labels:
    heritage: deckhouse
    module: node-manager
spec:
  group: infrastructure.cluster.x-k8s.io
  # cluster wide resource because we will refer for this from node group (cluster wide object)
  names:
    kind: StaticMachine
    plural: staticmachinetemplates
    singular: staticmachine
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Age
          type: date
          description: >
            CreationTimestamp is a timestamp representing the server time when this object was created.
            It is not guaranteed to be set in happens-before order across separate operations.
            Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          description: |
            Defines static machine. It is machine implementation for Cluster API infrastructure.
          properties:
            spec:
              type: object
              description: Specification of the desired behavior of the static machine templates.
              properties:
                providerID:
                  type: string
                  description: |
                    The identifier for the provider’s machine instance.
                labelSelector:
                  type: object
                  description: |
                    Specifies the label selector to filter static instances with.

                    You can get more into [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).
                  anyOf:
                    - required:
                        - matchLabels
                    - required:
                        - matchExpressions
                  properties:
                    matchLabels:
                      type: object
                      description: List of labels which static instances should have.
                      example: { "foo": "bar", "baz": "who" }
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      description: List of label expressions for static instances.
                      example: |
                        ```yaml
                        matchExpressions:
                        - key: tier
                          operator: In
                          values:
                          - production
                          - staging
                        ```
                      items:
                        type: object
                        required:
                          - key
                          - operator
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                          values:
                            type: array
                            items:
                              type: string
                nodeTemplate:
                  description: |
                    Specification of some of the fields that will be maintained in all nodes of the group.
                  x-doc-example: |
                    ```yaml
                    labels:
                      environment: production
                      app: warp-drive-ai
                    annotations:
                      ai.fleet.com/discombobulate: "true"
                    taints:
                    - effect: NoExecute
                      key: ship-class
                      value: frigate
                    ```
                  type: object
                  properties:
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                      x-kubernetes-preserve-unknown-fields: true
                      description: |
                        Similar to the standard `metadata.labels` [field](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#objectmeta-v1-meta).
                      x-doc-example: |
                        ```yaml
                        labels:
                          environment: production
                          app: warp-drive-ai
                        ```
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                      x-kubernetes-preserve-unknown-fields: true
                      description: |
                        Similar to the standard `metadata.annotations` [field](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#objectmeta-v1-meta).
                      x-doc-example: |
                        ```yaml
                        annotations:
                          ai.fleet.com/discombobulate: "true"
                        ```
                    taints:
                      type: array
                      description: |
                        Similar to the `.spec.taints` field of the [Node](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#taint-v1-core) object.

                        **Caution!** Only `effect`, `key`, `value` fields are available.
                      x-doc-example: |
                        ```yaml
                        taints:
                        - effect: NoExecute
                          key: ship-class
                          value: frigate
                        ```
                      items:
                        type: object
                        properties:
                          effect:
                            type: string
                            enum:
                              - NoSchedule
                              - PreferNoSchedule
                              - NoExecute
                          key:
                            type: string
                          value:
                            type: string
            status:
              type: object
              description: Most recently observed status of the static instance.
              properties:
                ready:
                  type: boolean
                  description: Indicates the provider-specific infrastructure has been provisioned and is ready.
                addresses:
                  description: |
                    A list of the host names, external IP addresses, internal IP addresses, external DNS names,
                    and/or internal DNS names for the provider’s machine instance.
                  type: object
                  properties:
                    type:
                      type: string
                      description: Address type
                      enum: ["Hostname", "ExternalIP", "InternalIP", "ExternalDNS", "InternalDNS"]
                    address:
                      type: string
                      description: Address value
                failureReason:
                  type: string
                  description: Indicates there is a fatal problem reconciling the provider’s infrastructure; meant to be suitable for programmatic interpretation
                failureMessage:
                  type: string
                  description: Indicates there is a fatal problem reconciling the provider’s infrastructure; meant to be a more descriptive value than failureReason

